window.WB = window.WB || {};

WB.Config = {
    CANVAS_WIDTH: 540,
    CANVAS_HEIGHT: 960,
    ARENA: { x: 20, y: 70, width: 500, height: 780 },
    BALL_RADIUS: 30,
    BALL_MAX_HP: 100,
    BALL_MASS: 1.0,
    BALL_MAX_SPEED: 14,
    BALL_FRICTION: 0.9998,
    WALL_RESTITUTION: 1.12,
    BALL_RESTITUTION: 1.0,
    WEAPON_HIT_COOLDOWN: 15,
    SUPER_THRESHOLD: 10,
    // Physics modifier toggles
    INELASTIC_MODE: false,
    INELASTIC_BALL_RESTITUTION: 0.5,
    INELASTIC_WALL_RESTITUTION: 0.6,
    GRAVITY_MODE: true,
    GRAVITY: 0.15,
    GRAVITY_ANGLE: Math.PI / 2,  // radians, PI/2 = straight down (Set's super shifts this)
    WEAPON_WALL_BOUNCE: true,
    WEAPON_WALL_BOUNCE_STRENGTH: 3.0,
    WEAPON_WALL_DMG_BOUNCE: false,
    SUPERS_ENABLED: false,
    CUTSCENE_ENABLED: false,
    MOTION_BLUR_ENABLED: true,
    MOTION_BLUR_STRENGTH: 0.25,  // 0=off, 0.5=full 180° shutter, 0.25=subtle cinematic
    SIDEBAR_WIDTH: 0,             // px per side during battle (0 = no sidebars)
    // Stage size presets (index into STAGE_PRESETS)
    STAGE_SIZE_INDEX: 1,
    STAGE_PRESETS: [
        { label: 'SMALL',  width: 340, height: 540 },
        { label: 'SQUARE', width: 420, height: 420 },
        { label: 'MEDIUM', width: 500, height: 780 },
        { label: 'LARGE',  width: 500, height: 1200 },
        { label: 'HUGE',   width: 500, height: 1600 },
    ],
    // Friction presets (index into FRICTION_PRESETS)
    FRICTION_INDEX: 2,
    FRICTION_PRESETS: [
        { label: 'NONE',   value: 1.0 },
        { label: 'LOW',    value: 0.9999 },
        { label: 'MED',    value: 0.9998 },
        { label: 'HIGH',   value: 0.998 },
        { label: 'HEAVY',  value: 0.995 },
    ],
    // Pack/Season definitions
    PACKS: {
        classic:   { name: 'Classic',   color: '#888888' },
        elemental: { name: 'Elemental', color: '#5DAA8F' },
        pantheon:  { name: 'Pantheon',  color: '#DAA520' },
        egyptian:  { name: 'Egyptian',  color: '#C9A84C' },
        states:    { name: 'States',   color: '#3C3B6E' },
    },
    COLORS: {
        // Generic weapons — boosted saturation for Earclacks-style vividness
        sword:       '#FF5A5A',
        bow:         '#FFE600',
        hammer:      '#D24E86',
        shuriken:    '#99AA00',
        sawblade:    '#FF6600',
        ghost:       '#88DDFF',
        clacker:     '#B8B8B8',
        gunclacker:  '#AA8500',
        // Elemental weapons
        fire:        '#FF4411',
        ice:         '#66CCFF',
        spark:       '#FFE333',
        stone:       '#8B7355',
        wind:        '#77DDBB',
        water:       '#3388DD',
        poison:      '#66CC33',
        light:       '#FFEE88',
        shadow:      '#553388',
        nature:      '#33AA44',
        crystal:     '#CC66FF',
        magma:       '#FF6622',
        storm:       '#7744CC',
        metal:       '#8899BB',
        gravity:     '#220044',
        // Greek Pantheon weapons
        zeus:        '#FFD700',
        poseidon:    '#00AAAA',
        ares:        '#DC143C',
        athena:      '#D0D0D0',
        apollo:      '#FFA500',
        artemis:     '#228B22',
        hephaestus:  '#CC5500',
        hermes:      '#66CCEE',
        hades:       '#4A0E8F',
        dionysus:    '#8B00FF',
        // Egyptian Pantheon weapons
        thoth:       '#2828AA',
        ra:          '#FFD700',
        sekhmet:     '#8B0000',
        sobek:       '#006400',
        set:         '#C2452D',
        anubis:      '#333333',
        horus:       '#4169E1',
        khnum:       '#CD853F',
        wadjet:      '#00A86B',
        osiris:      '#98FB98',
        // US States (Season 3) — colors from spec
        'alabama':          '#990000',
        'alaska':           '#003366',
        'arizona':          '#C41E3A',
        'arkansas':         '#A0522D',
        'california':       '#FFD700',
        'colorado':         '#4B0082',
        'connecticut':      '#003B6F',
        'delaware':         '#00539B',
        'florida':          '#FF6600',
        'georgia':          '#FF4444',
        'hawaii':           '#FF0000',
        'idaho':            '#C5A253',
        'illinois':         '#0033A0',
        'indiana':          '#041E42',
        'iowa':             '#FFD700',
        'kansas':           '#006BA6',
        'kentucky':         '#7B3F00',
        'louisiana':        '#4B0082',
        'maine':            '#003F87',
        'maryland':         '#E03C31',
        'massachusetts':    '#1C2841',
        'michigan':         '#003B6F',
        'minnesota':        '#003B5C',
        'mississippi':      '#6B0C22',
        'missouri':         '#003B6F',
        'montana':          '#003366',
        'nebraska':         '#E41C38',
        'nevada':           '#C0C0C0',
        'new-hampshire':    '#263238',
        'new-jersey':       '#FFD700',
        'new-mexico':       '#FFD700',
        'new-york':         '#1C3C6E',
        'north-carolina':   '#4B9CD3',
        'north-dakota':     '#000000',
        'ohio':             '#E03C31',
        'oklahoma':         '#7B1113',
        'oregon':           '#0F4D2A',
        'pennsylvania':     '#002244',
        'rhode-island':     '#003DA5',
        'south-carolina':   '#7B1F3A',
        'south-dakota':     '#002776',
        'tennessee':        '#FF6B00',
        'texas':            '#BF0A30',
        'utah':             '#F0E68C',
        'vermont':          '#046A38',
        'virginia':         '#002147',
        'washington':       '#2D572C',
        'west-virginia':    '#002855',
        'wisconsin':        '#204C23',
        'wyoming':          '#FFC425',
        // DC & Territories (placeholders — not in Season 3 spec)
        'dc':               '#CC0000',
        'puerto-rico':      '#CC0000',
        'guam':             '#003DA5',
        'usvi':             '#FFD700',
        'american-samoa':   '#003DA5',
        'northern-mariana': '#003DA5',
    },
    WEAPON_NAMES: {
        // Generic weapons
        sword:       'Sword',
        bow:         'Bow',
        hammer:      'Hammer',
        shuriken:    'Shuriken',
        sawblade:    'Sawblade',
        ghost:       'Ghost',
        clacker:     'Clacker',
        gunclacker:  'Gunclacker',
        // Elemental weapons
        fire:        'Inferno',
        ice:         'Frostbite',
        spark:       'Volt Whip',
        stone:       'Boulder',
        wind:        'Gale Blade',
        water:       'Tidal Surge',
        poison:      'Toxic Barb',
        light:       'Prism Beam',
        shadow:      'Phantom Edge',
        nature:      'Vine Lash',
        crystal:     'Crystal Cage',
        magma:       'Lava Flow',
        storm:       'Thunder Hammer',
        metal:       'Iron Guard',
        gravity:     'Gravity Well',
        // Greek Pantheon weapons
        zeus:        'Zeus',
        poseidon:    'Poseidon',
        ares:        'Ares',
        athena:      'Athena',
        apollo:      'Apollo',
        artemis:     'Artemis',
        hephaestus:  'Hephaestus',
        hermes:      'Hermes',
        hades:       'Hades',
        dionysus:    'Dionysus',
        // Egyptian Pantheon weapons
        thoth:       'Thoth',
        ra:          'Ra',
        sekhmet:     'Sekhmet',
        sobek:       'Sobek',
        set:         'Set',
        anubis:      'Anubis',
        horus:       'Horus',
        khnum:       'Khnum',
        wadjet:      'Wadjet',
        osiris:      'Osiris',
        // US States & Territories
        'alabama':          'Alabama',
        'alaska':           'Alaska',
        'arizona':          'Arizona',
        'arkansas':         'Arkansas',
        'california':       'California',
        'colorado':         'Colorado',
        'connecticut':      'Connecticut',
        'delaware':         'Delaware',
        'florida':          'Florida',
        'georgia':          'Georgia',
        'hawaii':           'Hawaii',
        'idaho':            'Idaho',
        'illinois':         'Illinois',
        'indiana':          'Indiana',
        'iowa':             'Iowa',
        'kansas':           'Kansas',
        'kentucky':         'Kentucky',
        'louisiana':        'Louisiana',
        'maine':            'Maine',
        'maryland':         'Maryland',
        'massachusetts':    'Massachusetts',
        'michigan':         'Michigan',
        'minnesota':        'Minnesota',
        'mississippi':      'Mississippi',
        'missouri':         'Missouri',
        'montana':          'Montana',
        'nebraska':         'Nebraska',
        'nevada':           'Nevada',
        'new-hampshire':    'New Hampshire',
        'new-jersey':       'New Jersey',
        'new-mexico':       'New Mexico',
        'new-york':         'New York',
        'north-carolina':   'North Carolina',
        'north-dakota':     'North Dakota',
        'ohio':             'Ohio',
        'oklahoma':         'Oklahoma',
        'oregon':           'Oregon',
        'pennsylvania':     'Pennsylvania',
        'rhode-island':     'Rhode Island',
        'south-carolina':   'South Carolina',
        'south-dakota':     'South Dakota',
        'tennessee':        'Tennessee',
        'texas':            'Texas',
        'utah':             'Utah',
        'vermont':          'Vermont',
        'virginia':         'Virginia',
        'washington':       'Washington',
        'west-virginia':    'West Virginia',
        'wisconsin':        'Wisconsin',
        'wyoming':          'Wyoming',
        'dc':               'Washington D.C.',
        'puerto-rico':      'Puerto Rico',
        'guam':             'Guam',
        'usvi':             'US Virgin Islands',
        'american-samoa':   'American Samoa',
        'northern-mariana': 'N. Mariana Islands',
    }
};
