window.WB = window.WB || {};

WB.Config = {
    CANVAS_WIDTH: 900,
    CANVAS_HEIGHT: 780,
    ARENA: { x: 100, y: 90, width: 700, height: 440 },
    BALL_RADIUS: 30,
    BALL_MAX_HP: 100,
    BALL_MASS: 1.0,
    BALL_MAX_SPEED: 10,
    BALL_FRICTION: 0.9998,
    WALL_RESTITUTION: 1.0,
    BALL_RESTITUTION: 1.0,
    WEAPON_HIT_COOLDOWN: 15,
    SUPER_THRESHOLD: 10,
    NUDGE_INTERVAL: 90,   // frames between random velocity nudges
    NUDGE_STRENGTH: 1.2,
    COLORS: {
        sword:     '#E85D75',
        dagger:    '#7BCC70',
        bow:       '#F0D264',
        hammer:    '#D24E86',
        spear:     '#6BB5E0',
        scythe:    '#9B59B6',
        unarmed:   '#F5F5DC',
        lance:     '#DAA520',
        axe:       '#CF1301',
        shuriken:  '#858D08',
        boomerang: '#C5A000',
        crossbow:  '#7CB900',
        magnet:    '#DD3355',
        sawblade:    '#FF6600',
        duplicator:  '#00CC88',
        goku:        '#FF8C00',
        vegeta:      '#6644FF',
        ghost:       '#88DDFF',
        muscle:      '#CC4422',
        buu:         '#FF69B4',
        clacker:     '#C0C0C0',
        naruto:      '#FF8833',
        sasuke:      '#6633CC',
        luffy:       '#CC2222',
        zoro:        '#2E8B2E',
        ichigo:      '#FF6633',
        saitama:     '#FFD700',
        frieza:      '#CC44FF',
        jotaro:      '#6644CC',
        piccolo:     '#2E8B57',
        tanjiro:     '#44BBFF',
        gunclacker:  '#8B7500',
        sailormoon:  '#FFB6C1',
        david:       '#00FFFF',
        vash:        '#CC0000',
    },
    WEAPON_NAMES: {
        sword:     'Sword',
        dagger:    'Dagger',
        bow:       'Bow',
        hammer:    'Hammer',
        spear:     'Spear',
        scythe:    'Scythe',
        unarmed:   'Unarmed',
        lance:     'Lance',
        axe:       'Axe',
        shuriken:  'Shuriken',
        boomerang: 'Boomerang',
        crossbow:  'Crossbow',
        magnet:    'Magnet',
        sawblade:    'Sawblade',
        duplicator:  'Duplicator',
        goku:        'Goku',
        vegeta:      'Vegeta',
        ghost:       'Ghost',
        muscle:      'Muscle',
        buu:         'Majin Buu',
        clacker:     'Clacker',
        naruto:      'Naruto',
        sasuke:      'Sasuke',
        luffy:       'Luffy',
        zoro:        'Zoro',
        ichigo:      'Ichigo',
        saitama:     'Saitama',
        frieza:      'Frieza',
        jotaro:      'Jotaro',
        piccolo:     'Piccolo',
        tanjiro:     'Tanjiro',
        gunclacker:  'Gunclacker',
        sailormoon:  'Sailor Moon',
        david:       'David',
        vash:        'Vash',
    }
};
