window.WB = window.WB || {};

WB.Config = {
    CANVAS_WIDTH: 540,
    CANVAS_HEIGHT: 960,
    ARENA: { x: 20, y: 70, width: 500, height: 780 },
    BALL_RADIUS: 30,
    BALL_MAX_HP: 100,
    BALL_MASS: 1.0,
    BALL_MAX_SPEED: 10,
    BALL_FRICTION: 0.9998,
    WALL_RESTITUTION: 1.0,
    BALL_RESTITUTION: 1.0,
    WEAPON_HIT_COOLDOWN: 15,
    SUPER_THRESHOLD: 10,
    // Physics modifier toggles
    INELASTIC_MODE: false,
    INELASTIC_BALL_RESTITUTION: 0.5,
    INELASTIC_WALL_RESTITUTION: 0.6,
    GRAVITY_MODE: true,
    GRAVITY: 0.15,
    WEAPON_WALL_BOUNCE: true,
    WEAPON_WALL_BOUNCE_STRENGTH: 3.0,
    WEAPON_WALL_DMG_BOUNCE: false,
    COLORS: {
        // Generic weapons
        sword:       '#E85D75',
        bow:         '#F0D264',
        hammer:      '#D24E86',
        shuriken:    '#858D08',
        sawblade:    '#FF6600',
        ghost:       '#88DDFF',
        clacker:     '#C0C0C0',
        gunclacker:  '#8B7500',
        // Elemental weapons
        fire:        '#FF4411',
        ice:         '#66CCFF',
        spark:       '#FFE333',
        stone:       '#8B7355',
        wind:        '#AADDCC',
        water:       '#3388DD',
        poison:      '#66CC33',
        light:       '#FFEE88',
        shadow:      '#553388',
        nature:      '#33AA44',
        crystal:     '#CC66FF',
        magma:       '#FF6622',
        storm:       '#7744CC',
        metal:       '#AABBCC',
    },
    WEAPON_NAMES: {
        // Generic weapons
        sword:       'Sword',
        bow:         'Bow',
        hammer:      'Hammer',
        shuriken:    'Shuriken',
        sawblade:    'Sawblade',
        ghost:       'Ghost',
        clacker:     'Clacker',
        gunclacker:  'Gunclacker',
        // Elemental weapons
        fire:        'Inferno',
        ice:         'Frostbite',
        spark:       'Volt Whip',
        stone:       'Boulder',
        wind:        'Gale Blade',
        water:       'Tidal Surge',
        poison:      'Toxic Barb',
        light:       'Prism Beam',
        shadow:      'Phantom Edge',
        nature:      'Vine Lash',
        crystal:     'Crystal Cage',
        magma:       'Lava Flow',
        storm:       'Thunder Hammer',
        metal:       'Iron Guard',
    }
};
